language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
script:
  - bash -ex .travis-opam.sh
  - if [ ! -z "${XS_COV}" ]; then bash -ex travis-coveralls.sh || true; fi
env:
  global:
    - OCAML_VERSION=4.02
    - PACKAGE=xen-api-client
    # WARNING: Don't set TESTS=true here (which is the default) as that env var
    # is already used by the Makefile for OASIS configuration.
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam XS_COV=1
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
  fast_finish: true
  allow_failures:
    - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
