language: c
install: wget https://raw.githubusercontent.com/xapi-project/ocaml-travisci-skeleton/master/.travis-opam.sh
script: PACKAGE=xapi-forkexecd FORK_USER=xapi-project bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.01 PACKAGE=xapi-xenopsd FORK_USER=xapi-project EXTRA_REMOTES=git://github.com/xapi-project/opam-repo-dev
