language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - OCAML_VERSION=4.04
    - PINS="xen-api-client:."
    - PACKAGE=xen-api-client
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam POST_INSTALL_HOOK="env TRAVIS=$TRAVIS TRAVIS_JOB_ID=$TRAVIS_JOB_ID bash -ex .coverage.sh"
    - PACKAGE=xen-api-client-async BASE_REMOTE=git://github.com/xapi-project/xs-opam POST_INSTALL_HOOK="make async-examples"
    - PACKAGE=xen-api-client-lwt BASE_REMOTE=git://github.com/xapi-project/xs-opam POST_INSTALL_HOOL="make lwt-examples"
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
  fast_finish: true
  allow_failures:
    - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
