language: c
services: docker
os: linux
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
  - wget https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env
  - source xs-opam-ci.env
script: bash -ex .travis-docker.sh
env:
  global:
    - PINS="xapi-rrdd:. xapi-rrd-transport:. xapi-rrd-transport-utils:. rrddump:. rrd-transport:."
  jobs:
    - PACKAGE="xapi-rrdd"
    - PACKAGE="rrddump"
