language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
script: bash -ex .travis-opam.sh && bash -ex travis-coveralls.sh
sudo: required
env:
  global:
    - OCAML_VERSION=4.02
    - PACKAGE=message-switch
  matrix:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam COV_CONF="./configure"
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
    fast_finish: true
    allow_failures:
        - env: EXTRA_REMOTES=git://github.com/xapi-project/xs-opam

