language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE="xcp-networkd"
    - PINS="xcp-networkd:."
    - BASE_REMOTE="https://github.com/xcp-networkd-project/xs-opam.git"
  matrix:
    - DISTRO="debian-9-ocaml-4.06"
