language: c
os: linux
dist: xenial
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - wget https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env
  - . xs-opam-ci.env
  - bash -ex .travis-docker.sh
env:
  global:
    - PINS="xapi-xenopsd:. xapi-xenopsd-xc:. xapi-xenopsd-simulator:. xapi-xenopsd-cli:."
  jobs:
    - PACKAGE="xapi-xenopsd-xc"
