language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - OCAML_VERSION="4.07"
    - DISTRO="debian-unstable"
    - PACKAGE="xapi-tapctl"
    - PINS="xapi-tapctl:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
