language: c
sudo: required
services:
  - docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - bash -ex .travis-docker.sh
env:
  global:
    - DISTRO=debian-unstable
    - PACKAGE="ezxenstore"
    - PINS="ezxenstore:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
  matrix:
    - OCAML_VERSION="4.07"
