language: c
sudo: required
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
  - bash -ex .travis-opam.sh
env:
  global:
    - OCAML_VERSION=4.06
    - TESTS=false
    - PINS="xapi-storage-cli:."
  matrix:
    - EXTRA_REMOTES=git://github.com/xapi-project/xs-opam
matrix:
  fast_finish: true
