language: c
os: linux
dist: xenial
services: docker
script: bash ./.travis-$BUILD_METHOD.sh
env:
    jobs:
        - BUILD_METHOD=xs-opam
        - BUILD_METHOD=python-nosetests
        - BUILD_METHOD=python-nosetests-3
jobs:
    fast_finish: true
    allow_failures:
        - env: BUILD_METHOD=python-nosetests-3
