language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
env:
  global:
    - BASE_REMOTE=git://github.com/xapi-project/xs-opam
    - DISTRO="debian-9-ocaml-4.07"
    - PACKAGE=xapi-storage-script
    - PINS="xapi-storage-script:."
