name: Build and test

on:
  push:
  pull_request:

jobs:
  ocaml-test:
    name: Ocaml tests
    runs-on: ubuntu-20.04
    env:
      package: "xapi-networkd"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v0.2.5

      - name: Use ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repository: ${{ steps.dotenv.outputs.repository }}

      - name: Update opam metadata
        run: |
          opam update
          opam pin add . --no-action

      - name: Install external dependencies
        run: opam depext -u ${{ env.package }}

      - name: Install dependencies
        run: |
          opam upgrade
          opam install ${{ env.package }} --deps-only --with-test -v

      - name: Build
        run: opam exec -- make

      - name: Run tests
        run: opam exec -- make test
