name: Create release from tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      XAPI_VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          pip install build
          sudo apt-get install ocaml dune libfindlib-ocaml-dev libdune-ocaml-dev libcmdliner-ocaml-dev

      - name: Generate python package for XenAPI
        run: |
          ./configure --xapi-version=${{ github.ref_name }}
          make python

      - name: Draft Release ${{ github.ref_name }}
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scripts/examples/python/dist/*
          fail_on_unmatched_files: true
          draft: true
          generate_release_notes: true
