name: Check format

on:
  pull_request:
    branches:
      - master
      - 'feature/**'
      - '*-lcm'

jobs:
  ocaml-format:
    name: Ocaml files
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/xapi-project/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v1.0.2

      - name: Use ocaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repositories: |
            xs-opam: ${{ steps.dotenv.outputs.repository }}
          dune-cache: true

      - name: Install ocamlformat
        run: |
          opam update
          opam install ocamlformat

      - name: Check whether `make format` was run
        run: opam exec -- dune build @fmt
